#!/usr/bin/env node
/**
 * gap-agent.js — Gap-Filling Specialist Agent
 *
 * Detects stuck PRs, missing tests, and unwired tools.
 * Decomposes stuck tasks into atomic sub-tasks and writes a gap report.
 *
 * Usage:
 *   node gap-agent.js [--threshold <days>] [--output <path>]
 *
 * Called automatically by run-autowork-loop.sh when a PR is stuck > 24h.
 */

import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { detectGaps } from "./gap-detector.js";
import { decomposeAll, AGENTS } from "./task-decomposer.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

// ── Arg parsing ───────────────────────────────────────────────────────────────
const args = process.argv.slice(2);
const threshold = Number(args[args.indexOf("--threshold") + 1] || 1);
const outputPath = args[args.indexOf("--output") + 1] || join(__dirname, "gap-report.md");

// ── Detect ────────────────────────────────────────────────────────────────────
export function runGapAgent({ stuckDaysThreshold = threshold, nowMs = Date.now() } = {}) {
  const gaps = detectGaps({ stuckDaysThreshold, nowMs });

  const stuckPrs   = gaps.filter(g => g.type === "stuck_pr");
  const missingTests = gaps.filter(g => g.type === "missing_test");
  const unwiredTools = gaps.filter(g => g.type === "unwired_tool");

  // ── Decompose stuck tasks ─────────────────────────────────────────────────
  const dispatched = [];
  for (const pr of stuckPrs) {
    const decomposed = decomposeAll(pr.tasks);
    dispatched.push({ prId: pr.prId, decomposed });
  }

  return { gaps, stuckPrs, missingTests, unwiredTools, dispatched };
}

// ── Report ─────────────────────────────────────────────────────────────────────
export function buildReport(result, { nowMs = Date.now() } = {}) {
  const ts = new Date(nowMs).toISOString();
  const lines = [
    `# Gap Report — ${ts}`,
    "",
  ];

  if (result.stuckPrs.length === 0 && result.missingTests.length === 0 && result.unwiredTools.length === 0) {
    lines.push("No gaps detected. All PRs progressing, tests present, tools wired.");
    return lines.join("\n");
  }

  if (result.stuckPrs.length > 0) {
    lines.push("## Stuck PRs");
    for (const pr of result.stuckPrs) {
      lines.push(`\n### ${pr.prId} — ${pr.status} (${pr.ageDays}d stuck, ${pr.uncheckedTasks} tasks left)`);
      const item = result.dispatched.find(d => d.prId === pr.prId);
      if (item) {
        for (const d of item.decomposed) {
          const label = `[${d.agent.toUpperCase()}]`;
          if (d.isAtomic) {
            lines.push(`- ${label} ${d.original}`);
          } else {
            lines.push(`- ${label} (decomposed from: "${d.original}")`);
            for (const sub of d.subTasks) {
              lines.push(`  - [${sub.agent.toUpperCase()}] ${sub.text}`);
            }
          }
        }
      }
    }
    lines.push("");
  }

  if (result.missingTests.length > 0) {
    lines.push("## Modules Missing Tests");
    for (const g of result.missingTests) {
      lines.push(`- ${g.description}`);
    }
    lines.push("");
  }

  if (result.unwiredTools.length > 0) {
    lines.push("## Unwired Tools (no tool definition)");
    for (const g of result.unwiredTools) {
      lines.push(`- ${g.description}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(`Generated by gap-agent.js at ${ts}`);
  return lines.join("\n");
}

// ── CLI entry ─────────────────────────────────────────────────────────────────
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const result = runGapAgent({ stuckDaysThreshold: threshold });
  const report = buildReport(result);
  writeFileSync(outputPath, report);
  process.stdout.write(report + "\n");
  process.exitCode = result.stuckPrs.length > 0 ? 1 : 0;
}
