/**
 * vault-writer.js — writes agent decisions back to the Obsidian vault.
 * Appends entries to 05-Decisions/auto-YYYY-MM-DD.md so the agent
 * builds institutional memory it can read next cycle via getVaultContext().
 *
 * Never throws. Vault writes are best-effort and must not affect bot operation.
 */
import fs from "fs";
import path from "path";
import { atomicWriteText } from "../atomic-write.js";

const DEFAULT_VAULT_FILE = "/home/ubuntu/ponyou-brain/operator-notes.md";

function _ymd(d = new Date()) {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

function _hm(d = new Date()) {
  const h = String(d.getHours()).padStart(2, "0");
  const m = String(d.getMinutes()).padStart(2, "0");
  return `${h}:${m}`;
}

/** Resolved vault dir — exported for tests. */
export function _getVaultWriterDir() {
  return path.dirname(process.env.PONYOU_VAULT_NOTES_FILE || DEFAULT_VAULT_FILE);
}

function _extractToken(decision) {
  const d = String(decision || "");
  // $SYMBOL
  const dollar = d.match(/\$([A-Za-z0-9_]{2,15})/);
  if (dollar) return dollar[1];
  // "symbol":"SYMBOL"
  const sym = d.match(/"symbol"\s*:\s*"([^"]{2,20})"/i);
  if (sym) return sym[1];
  // BUY SYMBOL
  const buy = d.match(/\bBUY\b[\s:]+([A-Za-z0-9_]{2,15})/i);
  if (buy) return buy[1];
  return "";
}

function _detectType(decision) {
  const lower = String(decision || "").toLowerCase();
  // dry_run is an explicit paper-buy signal — check it before BUY
  if (lower.includes("dry_run")) return { type: "PAPER-BUY", token: _extractToken(decision) };
  if (lower.includes("swap_token") || lower.includes("buy")) return { type: "BUY", token: _extractToken(decision) };
  return { type: "SKIP", token: "" };
}

function _briefReason(decision) {
  let s = String(decision || "");
  s = s.replace(/\{[\s\S]*?\}/g, " "); // strip JSON blobs
  s = s.replace(/[\r\n]+/g, " ");       // strip newlines
  s = s.replace(/\s+/g, " ").trim();    // collapse whitespace
  return s.slice(0, 120);
}

/**
 * Append a trade outcome entry to today's decision log.
 * Closes the feedback loop: decision → execution → outcome, all in one daily file.
 * Never throws.
 *
 * @param {object} args
 * @param {string} args.symbol
 * @param {string} args.mint
 * @param {number} args.pnl_pct      realized PnL %
 * @param {number} args.hold_minutes
 * @param {string} args.exit_reason
 * @param {boolean} args.is_win
 */
export async function logTradeOutcome({ symbol, mint, pnl_pct, hold_minutes, exit_reason, is_win } = {}) {
  try {
    const sym = String(symbol || mint || "?").toUpperCase().slice(0, 20);
    const pnl = Number.isFinite(pnl_pct) ? pnl_pct : 0;
    const hold = Number.isFinite(hold_minutes) ? Math.round(hold_minutes) : 0;
    const reason = String(exit_reason || "").replace(/[\r\n]+/g, " ").trim().slice(0, 80);
    const label = is_win ? `WIN +${pnl.toFixed(1)}%` : `LOSS ${pnl.toFixed(1)}%`;

    const now = new Date();
    const entry =
      `\n## ${_hm(now)} — OUTCOME: ${sym}\n\n` +
      `**${label}** | ${hold}m | Exit: ${reason}\n\n` +
      `---\n`;

    const vaultDir = _getVaultWriterDir();
    const decDir = path.join(vaultDir, "05-Decisions");
    const file = path.join(decDir, `auto-${_ymd(now)}.md`);

    if (!fs.existsSync(file)) {
      const ymd = _ymd(now);
      const header =
        `---\n` +
        `tags: [decisions, auto-generated]\n` +
        `date: ${ymd}\n` +
        `type: auto-decision-log\n` +
        `---\n\n` +
        `# Auto Decision Log — ${ymd}\n\n` +
        `_Generated by bot. Each entry = one screening cycle decision._\n`;
      atomicWriteText(file, header);
    }

    fs.appendFileSync(file, entry);
  } catch {
    // best-effort: never throw
  }
}

/**
 * Append a brief markdown entry for one screening cycle decision.
 * Never throws — all errors silently swallowed.
 *
 * @param {object}   args
 * @param {object[]} args.candidates       token objects (.symbol, .mcap, .rug_score, .mint)
 * @param {string}   args.decision         raw LLM screenReport content
 * @param {string}   args.marketCondition  "HOT" | "COLD" | "NORMAL" | "DEAD"
 * @param {number}   args.deployAmount     SOL amount
 */
export async function logScreeningDecision({ candidates, decision, marketCondition, deployAmount } = {}) {
  try {
    const cands = Array.isArray(candidates) ? candidates : [];
    const { type, token } = _detectType(decision);
    const reason = _briefReason(decision);

    const top = cands
      .slice(0, 3)
      .map(c => `${c?.symbol ?? "?"}(rug=${c?.rug_score ?? "?"})`)
      .join(", ");

    const now = new Date();
    const ymd = _ymd(now);

    const entry =
      `\n## ${_hm(now)} — ${marketCondition} | ${cands.length} candidates\n\n` +
      `**${type}**${type === "BUY" && token ? ` ${token}` : ""} — ${deployAmount} SOL\n` +
      `Top tokens: ${top}\n` +
      `Reason: ${reason}\n\n` +
      `---\n`;

    const vaultDir = _getVaultWriterDir();
    const decDir = path.join(vaultDir, "05-Decisions");
    const file = path.join(decDir, `auto-${ymd}.md`);

    if (!fs.existsSync(file)) {
      const header =
        `---\n` +
        `tags: [decisions, auto-generated]\n` +
        `date: ${ymd}\n` +
        `type: auto-decision-log\n` +
        `---\n\n` +
        `# Auto Decision Log — ${ymd}\n\n` +
        `_Generated by bot. Each entry = one screening cycle decision._\n`;
      // atomic create (tmp+rename) — satisfies atomic-write regression guard
      atomicWriteText(file, header);
    }

    fs.appendFileSync(file, entry);
  } catch {
    // best-effort: never throw
  }
}
