/**
 * vault-writer.js — writes agent decisions back to the Obsidian vault.
 * Appends entries to 05-Decisions/auto-YYYY-MM-DD.md so the agent
 * builds institutional memory it can read next cycle via getVaultContext().
 *
 * Never throws. Vault writes are best-effort and must not affect bot operation.
 */
import fs from "fs";
import path from "path";
import { atomicWriteText } from "../atomic-write.js";

const DEFAULT_VAULT_FILE = "/home/ubuntu/ponyou-brain/operator-notes.md";

function _ymd(d = new Date()) {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

function _hm(d = new Date()) {
  const h = String(d.getHours()).padStart(2, "0");
  const m = String(d.getMinutes()).padStart(2, "0");
  return `${h}:${m}`;
}

/** Resolved vault dir — exported for tests. */
export function _getVaultWriterDir() {
  return path.dirname(process.env.PONYOU_VAULT_NOTES_FILE || DEFAULT_VAULT_FILE);
}

function _extractToken(decision) {
  const d = String(decision || "");
  // $SYMBOL
  const dollar = d.match(/\$([A-Za-z0-9_]{2,15})/);
  if (dollar) return dollar[1];
  // "symbol":"SYMBOL"
  const sym = d.match(/"symbol"\s*:\s*"([^"]{2,20})"/i);
  if (sym) return sym[1];
  // BUY SYMBOL
  const buy = d.match(/\bBUY\b[\s:]+([A-Za-z0-9_]{2,15})/i);
  if (buy) return buy[1];
  return "";
}

function _detectType(decision) {
  const lower = String(decision || "").toLowerCase();
  // dry_run is an explicit paper-buy signal — check it before BUY
  if (lower.includes("dry_run")) return { type: "PAPER-BUY", token: _extractToken(decision) };
  if (lower.includes("swap_token") || lower.includes("buy")) return { type: "BUY", token: _extractToken(decision) };
  return { type: "SKIP", token: "" };
}

function _briefReason(decision) {
  let s = String(decision || "");
  s = s.replace(/\{[\s\S]*?\}/g, " "); // strip JSON blobs
  s = s.replace(/[\r\n]+/g, " ");       // strip newlines
  s = s.replace(/\s+/g, " ").trim();    // collapse whitespace
  return s.slice(0, 120);
}

/**
 * Append a trade outcome entry to today's decision log.
 * Closes the feedback loop: decision → execution → outcome, all in one daily file.
 * Never throws.
 *
 * @param {object} args
 * @param {string} args.symbol
 * @param {string} args.mint
 * @param {number} args.pnl_pct      realized PnL %
 * @param {number} args.hold_minutes
 * @param {string} args.exit_reason
 * @param {boolean} args.is_win
 */
export async function logTradeOutcome({ symbol, mint, pnl_pct, hold_minutes, exit_reason, is_win } = {}) {
  try {
    const sym = String(symbol || mint || "?").toUpperCase().slice(0, 20);
    const pnl = Number.isFinite(pnl_pct) ? pnl_pct : 0;
    const hold = Number.isFinite(hold_minutes) ? Math.round(hold_minutes) : 0;
    const reason = String(exit_reason || "").replace(/[\r\n]+/g, " ").trim().slice(0, 80);
    const label = is_win ? `WIN +${pnl.toFixed(1)}%` : `LOSS ${pnl.toFixed(1)}%`;

    const now = new Date();
    const entry =
      `\n## ${_hm(now)} — OUTCOME: ${sym}\n\n` +
      `**${label}** | ${hold}m | Exit: ${reason}\n\n` +
      `---\n`;

    const vaultDir = _getVaultWriterDir();
    const decDir = path.join(vaultDir, "05-Decisions");
    const file = path.join(decDir, `auto-${_ymd(now)}.md`);

    if (!fs.existsSync(file)) {
      const ymd = _ymd(now);
      const header =
        `---\n` +
        `tags: [decisions, auto-generated]\n` +
        `date: ${ymd}\n` +
        `type: auto-decision-log\n` +
        `---\n\n` +
        `# Auto Decision Log — ${ymd}\n\n` +
        `_Generated by bot. Each entry = one screening cycle decision._\n`;
      atomicWriteText(file, header);
    }

    fs.appendFileSync(file, entry);
  } catch {
    // best-effort: never throw
  }
}

/**
 * Append a brief markdown entry for one screening cycle decision.
 * Never throws — all errors silently swallowed.
 *
 * @param {object}   args
 * @param {object[]} args.candidates       token objects (.symbol, .mcap, .rug_score, .mint)
 * @param {string}   args.decision         raw LLM screenReport content
 * @param {string}   args.marketCondition  "HOT" | "COLD" | "NORMAL" | "DEAD"
 * @param {number}   args.deployAmount     SOL amount
 */
export async function logScreeningDecision({ candidates, decision, marketCondition, deployAmount } = {}) {
  try {
    const cands = Array.isArray(candidates) ? candidates : [];
    const { type, token } = _detectType(decision);
    const reason = _briefReason(decision);

    const top = cands
      .slice(0, 3)
      .map(c => `${c?.symbol ?? "?"}(rug=${c?.rug_score ?? "?"})`)
      .join(", ");

    const now = new Date();
    const ymd = _ymd(now);

    const entry =
      `\n## ${_hm(now)} — ${marketCondition} | ${cands.length} candidates\n\n` +
      `**${type}**${type === "BUY" && token ? ` ${token}` : ""} — ${deployAmount} SOL\n` +
      `Top tokens: ${top}\n` +
      `Reason: ${reason}\n\n` +
      `---\n`;

    const vaultDir = _getVaultWriterDir();
    const decDir = path.join(vaultDir, "05-Decisions");
    const file = path.join(decDir, `auto-${ymd}.md`);

    if (!fs.existsSync(file)) {
      const header =
        `---\n` +
        `tags: [decisions, auto-generated]\n` +
        `date: ${ymd}\n` +
        `type: auto-decision-log\n` +
        `---\n\n` +
        `# Auto Decision Log — ${ymd}\n\n` +
        `_Generated by bot. Each entry = one screening cycle decision._\n`;
      // atomic create (tmp+rename) — satisfies atomic-write regression guard
      atomicWriteText(file, header);
    }

    fs.appendFileSync(file, entry);
  } catch {
    // best-effort: never throw
  }
}

// ─── Snapshot writers ──────────────────────────────────────────────────────
// Bot-owned markdown mirrors of in-process data. Operator reads these in
// Obsidian. Each function is fully independent and never throws.

function _ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

/** 20-Devs/_blacklist.md — mirror of getDevBlacklist() */
export async function writeDevBlacklistSnapshot() {
  try {
    const { getDevBlacklist } = await import("./dev-blacklist.js");
    const vaultDir = _getVaultWriterDir();
    const dir = path.join(vaultDir, "20-Devs");
    _ensureDir(dir);
    const bl = getDevBlacklist();
    const now = new Date().toISOString();
    const recent = (bl.entries || []).slice(0, 12);
    const tiers = { CRITICAL: [], HIGH: [], MEDIUM: [], LOW: [] };
    for (const e of recent) {
      const t = e.tier || "LOW";
      if (tiers[t]) tiers[t].push(e);
    }
    const tierLines = t => tiers[t].map(e => {
      const exp  = e.expires_at ? ` expires ${e.expires_at.slice(0, 10)}` : "";
      const rugs = e.rug_count > 1 ? ` (${e.rug_count}×)` : "";
      return `- \`${(e.creator || "?").slice(0, 12)}…\`${rugs} — ${(e.reason || "").slice(0, 50)}${exp}`;
    }).join("\n");

    const body =
      `---\ntype: bot-snapshot\nupdated: ${now}\ntotal: ${bl.total}\ncritical: ${bl.critical}\nhigh: ${bl.high}\nmedium: ${bl.medium}\nlow: ${bl.low}\n---\n\n` +
      `# Dev Blacklist — ${bl.total} active (${bl.critical} CRITICAL, ${bl.high} HIGH, ${bl.medium} MEDIUM, ${bl.low} LOW)\n\n` +
      `_Auto-generated. Edit \`dev-overrides.md\` to trust/distrust a dev._\n\n` +
      (tiers.CRITICAL.length ? `## CRITICAL (permanent)\n${tierLines("CRITICAL")}\n\n` : "") +
      (tiers.HIGH.length     ? `## HIGH (30d)\n${tierLines("HIGH")}\n\n`    : "") +
      (tiers.MEDIUM.length   ? `## MEDIUM (14d)\n${tierLines("MEDIUM")}\n\n` : "") +
      (tiers.LOW.length      ? `## LOW (7d)\n${tierLines("LOW")}\n\n`       : "") +
      (bl.total === 0 ? "_No entries yet._\n" : "");
    atomicWriteText(path.join(dir, "_blacklist.md"), body);
  } catch { /* best-effort */ }
}

/** 10-SmartMoney/_live.md — mirror of top discovered wallets */
export async function writeSmartMoneyLive() {
  try {
    const { listDiscoveredWallets } = await import("./wallet-discovery.js");
    const vaultDir = _getVaultWriterDir();
    const dir = path.join(vaultDir, "10-SmartMoney");
    _ensureDir(dir);
    const wallets = listDiscoveredWallets({ qualified_only: true, limit: 20 });
    const now     = new Date().toISOString();
    const count   = wallets.length;
    const avgWr   = count > 0
      ? wallets.reduce((s, w) => s + (w.stats?.win_rate || 0), 0) / count
      : 0;
    const topSyms = wallets
      .flatMap(w => (w.source_tokens || []).slice(0, 2))
      .filter((s, i, a) => s && a.indexOf(s) === i)
      .slice(0, 6)
      .join(", ");

    const rows = wallets.slice(0, 15).map(w => {
      const addr = (w.address || "?").slice(0, 8) + "…";
      const wr   = w.stats?.win_rate != null ? `${(w.stats.win_rate * 100).toFixed(0)}%` : "?";
      const pnl  = w.stats?.realized_pnl_sol != null ? `${w.stats.realized_pnl_sol.toFixed(2)}` : "?";
      const tr   = w.stats?.total_trades || 0;
      return `| ${addr} | ${wr} | ${pnl} | ${tr} |`;
    }).join("\n");

    const body =
      `---\ntype: bot-snapshot\nupdated: ${now}\nwallet_count: ${count}\navg_winrate: ${avgWr.toFixed(3)}\ntop_symbols: "${topSyms}"\n---\n\n` +
      `# Smart Money — Top Proven Wallets\n\n` +
      `_Auto-generated. Edit \`follow-overrides.md\` to boost/mute wallets._\n\n` +
      `${count} qualified wallets tracked${avgWr > 0 ? ` | avg win rate ${(avgWr * 100).toFixed(0)}%` : ""}\n\n` +
      (rows ? `| wallet | win rate | PnL (SOL) | trades |\n|--------|----------|-----------|--------|\n${rows}\n` : "_No qualified wallets yet._\n");
    atomicWriteText(path.join(dir, "_live.md"), body);
  } catch { /* best-effort */ }
}

/** 30-Narratives/_heat.md — mirror of getNarrativeHeat() */
export async function writeNarrativeHeat() {
  try {
    const { getNarrativeHeat } = await import("./narratives.js");
    const vaultDir = _getVaultWriterDir();
    const dir      = path.join(vaultDir, "30-Narratives");
    _ensureDir(dir);
    const heat = getNarrativeHeat({ min_trades: 2, include_emerging: true });
    const now  = new Date().toISOString();

    const mkRow = n => {
      const wr  = n.winrate != null ? `${(n.winrate * 100).toFixed(0)}%` : "?";
      const pnl = n.avg_pnl_pct != null ? `${n.avg_pnl_pct > 0 ? "+" : ""}${n.avg_pnl_pct.toFixed(0)}%` : "?";
      return `| ${n.narrative} | ${wr} | ${pnl} | ${n.trades || "?"} |`;
    };
    const tbl = arr => arr.length
      ? `| narrative | win rate | avg PnL | trades |\n|-----------|----------|---------|--------|\n${arr.map(mkRow).join("\n")}\n`
      : "_None yet._\n";

    const hotItems  = heat.hot_items      || heat.ranked?.filter(n => n.winrate >= 0.55) || [];
    const coldItems = heat.cold_items     || heat.ranked?.filter(n => n.winrate < 0.4)   || [];
    const emItems   = heat.emerging_items || heat.emerging_list?.map(name => ({ narrative: name, tier: "emerging" })) || [];

    const body =
      `---\ntype: bot-snapshot\nupdated: ${now}\n---\n\n` +
      `# Narrative Heat\n\n` +
      `_Auto-generated. Adjust \`focus_narrative\` / \`blacklist_narratives\` in \`operator-notes.md\` to override._\n\n` +
      `## 🔥 Hot (winning)\n${tbl(hotItems)}\n` +
      `## ❄️ Cold (losing)\n${tbl(coldItems)}\n` +
      `## 🌱 Emerging (watch)\n${tbl(emItems)}\n`;
    atomicWriteText(path.join(dir, "_heat.md"), body);
  } catch { /* best-effort */ }
}

/** 40-RugPatterns/_active.md — mirror of listPatterns(), with vault-approve side-effect */
export async function writeActiveRugPatterns() {
  try {
    const { listPatterns, approvePattern } = await import("./rug-patterns.js");
    const { getPatternOverrides } = await import("./vault-reader.js");
    const vaultDir = _getVaultWriterDir();
    const dir      = path.join(vaultDir, "40-RugPatterns");
    _ensureDir(dir);
    const pats      = listPatterns();
    const overrides = getPatternOverrides();
    const now       = new Date().toISOString();

    // Apply vault-approved patterns (idempotent)
    for (const id of overrides.approve) {
      try { approvePattern(id, { approvedBy: "vault-operator" }); } catch { /* skip */ }
    }
    const muted = new Set(overrides.mute);

    const seedRows = (pats.seed_patterns || []).slice(0, 10).map(p =>
      `- \`${p.id || p.name}\` (w${p.weight || "?"}) — ${(p.description || p.reason || "").slice(0, 60)}`
    ).join("\n") || "_None._";

    const learnedRows = (pats.learned_patterns || []).slice(0, 15).map(p => {
      const mutedTag  = muted.has(p.id) ? " 🔇 MUTED" : "";
      const statusTag = p.review_status === "approved" ? " ✅" : " ⏳ PENDING REVIEW";
      const conf      = p.confidence != null ? ` conf ${p.confidence.toFixed(2)}` : "";
      const occ       = p.occurrences != null ? ` ${p.occurrences}×` : "";
      return `- \`${p.id}\` (w${p.weight || "?"}${conf}${occ})${statusTag}${mutedTag} — ${(p.description || "").slice(0, 50)}`;
    }).join("\n") || "_None learned yet._";

    const body =
      `---\ntype: bot-snapshot\nupdated: ${now}\nseed_count: ${pats.seed}\nlearned_count: ${pats.learned}\npending_review: ${pats.pending_learned}\n---\n\n` +
      `# Rug Patterns — ${pats.seed} seed, ${pats.learned} learned (${pats.pending_learned} pending review)\n\n` +
      `_Auto-generated. Add IDs to \`pattern-overrides.md\` (\`approve_patterns\` / \`mute_patterns\`) to act._\n\n` +
      `## Seed (hard rules)\n${seedRows}\n\n` +
      `## Learned (auto)\n${learnedRows}\n`;
    atomicWriteText(path.join(dir, "_active.md"), body);
  } catch { /* best-effort */ }
}

/**
 * Refresh all vault snapshots. Called on the 5-min cron.
 * Each snapshot runs independently — one failure never blocks the others.
 */
export async function refreshVaultSnapshots() {
  await Promise.allSettled([
    writeDevBlacklistSnapshot(),
    writeSmartMoneyLive(),
    writeNarrativeHeat(),
    writeActiveRugPatterns(),
  ]);
}
