/**
 * vault-writer.js — writes agent decisions back to the Obsidian vault.
 * Appends entries to 05-Decisions/auto-YYYY-MM-DD.md so the agent
 * builds institutional memory it can read next cycle via getVaultContext().
 *
 * Never throws. Vault writes are best-effort and must not affect bot operation.
 */
import fs from "fs";
import path from "path";
import { atomicWriteText } from "../atomic-write.js";

const DEFAULT_VAULT_FILE = "/home/ubuntu/ponyou-brain/operator-notes.md";

function _ymd(d = new Date()) {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

function _hm(d = new Date()) {
  const h = String(d.getHours()).padStart(2, "0");
  const m = String(d.getMinutes()).padStart(2, "0");
  return `${h}:${m}`;
}

/** Resolved vault dir — exported for tests. */
export function _getVaultWriterDir() {
  return path.dirname(process.env.PONYOU_VAULT_NOTES_FILE || DEFAULT_VAULT_FILE);
}

function _extractToken(decision) {
  const d = String(decision || "");
  // $SYMBOL
  const dollar = d.match(/\$([A-Za-z0-9_]{2,15})/);
  if (dollar) return dollar[1];
  // "symbol":"SYMBOL"
  const sym = d.match(/"symbol"\s*:\s*"([^"]{2,20})"/i);
  if (sym) return sym[1];
  // BUY SYMBOL
  const buy = d.match(/\bBUY\b[\s:]+([A-Za-z0-9_]{2,15})/i);
  if (buy) return buy[1];
  return "";
}

function _detectType(decision) {
  const lower = String(decision || "").toLowerCase();
  // dry_run is an explicit paper-buy signal — check it before BUY
  if (lower.includes("dry_run")) return { type: "PAPER-BUY", token: _extractToken(decision) };
  if (lower.includes("swap_token") || lower.includes("buy")) return { type: "BUY", token: _extractToken(decision) };
  return { type: "SKIP", token: "" };
}

function _briefReason(decision) {
  let s = String(decision || "");
  s = s.replace(/\{[\s\S]*?\}/g, " "); // strip JSON blobs
  s = s.replace(/[\r\n]+/g, " ");       // strip newlines
  s = s.replace(/\s+/g, " ").trim();    // collapse whitespace
  return s.slice(0, 120);
}

/**
 * Append a trade outcome entry to today's decision log.
 * Closes the feedback loop: decision → execution → outcome, all in one daily file.
 * Never throws.
 *
 * @param {object} args
 * @param {string} args.symbol
 * @param {string} args.mint
 * @param {number} args.pnl_pct      realized PnL %
 * @param {number} args.hold_minutes
 * @param {string} args.exit_reason
 * @param {boolean} args.is_win
 */
export async function logTradeOutcome({ symbol, mint, pnl_pct, hold_minutes, exit_reason, is_win } = {}) {
  try {
    const sym = String(symbol || mint || "?").toUpperCase().slice(0, 20);
    const pnl = Number.isFinite(pnl_pct) ? pnl_pct : 0;
    const hold = Number.isFinite(hold_minutes) ? Math.round(hold_minutes) : 0;
    const reason = String(exit_reason || "").replace(/[\r\n]+/g, " ").trim().slice(0, 80);
    const label = is_win ? `WIN +${pnl.toFixed(1)}%` : `LOSS ${pnl.toFixed(1)}%`;

    const now = new Date();
    const entry =
      `\n## ${_hm(now)} — OUTCOME: ${sym}\n\n` +
      `**${label}** | ${hold}m | Exit: ${reason}\n\n` +
      `---\n`;

    const vaultDir = _getVaultWriterDir();
    const decDir = path.join(vaultDir, "05-Decisions");
    const file = path.join(decDir, `auto-${_ymd(now)}.md`);

    if (!fs.existsSync(file)) {
      const ymd = _ymd(now);
      const header =
        `---\n` +
        `tags: [decisions, auto-generated]\n` +
        `date: ${ymd}\n` +
        `type: auto-decision-log\n` +
        `---\n\n` +
        `# Auto Decision Log — ${ymd}\n\n` +
        `_Generated by bot. Each entry = one screening cycle decision._\n`;
      atomicWriteText(file, header);
    }

    fs.appendFileSync(file, entry);
  } catch {
    // best-effort: never throw
  }
}

/**
 * Append a brief markdown entry for one screening cycle decision.
 * Never throws — all errors silently swallowed.
 *
 * @param {object}   args
 * @param {object[]} args.candidates       token objects (.symbol, .mcap, .rug_score, .mint)
 * @param {string}   args.decision         raw LLM screenReport content
 * @param {string}   args.marketCondition  "HOT" | "COLD" | "NORMAL" | "DEAD"
 * @param {number}   args.deployAmount     SOL amount
 */
export async function logScreeningDecision({ candidates, decision, marketCondition, deployAmount } = {}) {
  try {
    const cands = Array.isArray(candidates) ? candidates : [];
    const { type, token } = _detectType(decision);
    const reason = _briefReason(decision);

    const top = cands
      .slice(0, 3)
      .map(c => `${c?.symbol ?? "?"}(rug=${c?.rug_score ?? "?"})`)
      .join(", ");

    const now = new Date();
    const ymd = _ymd(now);

    const entry =
      `\n## ${_hm(now)} — ${marketCondition} | ${cands.length} candidates\n\n` +
      `**${type}**${type === "BUY" && token ? ` ${token}` : ""} — ${deployAmount} SOL\n` +
      `Top tokens: ${top}\n` +
      `Reason: ${reason}\n\n` +
      `---\n`;

    const vaultDir = _getVaultWriterDir();
    const decDir = path.join(vaultDir, "05-Decisions");
    const file = path.join(decDir, `auto-${ymd}.md`);

    if (!fs.existsSync(file)) {
      const header =
        `---\n` +
        `tags: [decisions, auto-generated]\n` +
        `date: ${ymd}\n` +
        `type: auto-decision-log\n` +
        `---\n\n` +
        `# Auto Decision Log — ${ymd}\n\n` +
        `_Generated by bot. Each entry = one screening cycle decision._\n`;
      // atomic create (tmp+rename) — satisfies atomic-write regression guard
      atomicWriteText(file, header);
    }

    fs.appendFileSync(file, entry);
  } catch {
    // best-effort: never throw
  }
}

/**
 * Log tokens that were SKIPPED before reaching the LLM (rule-based rejection).
 * These are high-rug or Kelly-rejected tokens — the operator can see what the
 * rug defense caught. Appended to same daily file as decisions.
 * Never throws.
 *
 * @param {object[]} skipped  — array of { symbol, mint, rug_score, flags[] }
 * @param {string}   marketCondition
 */
export async function logSkippedTokens(skipped = [], marketCondition = "UNKNOWN") {
  try {
    if (!skipped || skipped.length === 0) return;
    const vaultDir = _getVaultWriterDir();
    const decDir   = path.join(vaultDir, "05-Decisions");
    const now  = new Date();
    const file = path.join(decDir, `auto-${_ymd(now)}.md`);

    const topSkips = skipped.slice(0, 5).map(c => {
      const reason = (Array.isArray(c.flags) ? c.flags.slice(0, 2).join(", ") : "rug_score");
      return `  - ${c.symbol || "?"} rug=${c.rug_score ?? "?"} → ${reason.slice(0, 80)}`;
    }).join("\n");

    const entry =
      `\n## ${_hm(now)} — BLOCKED: ${skipped.length} tokens (${marketCondition})\n\n` +
      `_Rule-based rejection (rug score ≥ 60 or Kelly skip). Never reached LLM._\n` +
      `${topSkips}\n\n---\n`;

    if (!fs.existsSync(file)) {
      const ymd = _ymd(now);
      atomicWriteText(file, `---\ntags: [decisions, auto-generated]\ndate: ${ymd}\ntype: auto-decision-log\n---\n\n# Auto Decision Log — ${ymd}\n\n_Generated by bot._\n`);
    }
    fs.appendFileSync(file, entry);
  } catch { /* best-effort */ }
}

/**
 * Append a user-provided lesson/preference to operator-lessons.md.
 * Called by general agent when user says "remember X".
 * Creates the file if it doesn't exist.
 * Never throws.
 *
 * @param {string} lesson    — the text to remember (natural language)
 * @param {string} [source]  — "user" | "bot" | "auto"
 */
export async function appendOperatorLesson(lesson, source = "user") {
  try {
    if (!lesson || typeof lesson !== "string" || lesson.trim().length < 3) return;
    const vaultDir = _getVaultWriterDir();
    const file = path.join(vaultDir, "operator-lessons.md");
    const now = new Date();
    const tag  = source === "user" ? "👤 User" : source === "bot" ? "🤖 Bot" : "📝";

    const entry = `\n### ${tag} — ${_ymd(now)} ${_hm(now)}\n${lesson.trim()}\n`;

    if (!fs.existsSync(file)) {
      atomicWriteText(file, `# Operator Lessons\n\n_Wisdom dari operator dan bot. Dibaca sebelum setiap keputusan screening._\n`);
    }
    fs.appendFileSync(file, entry);
  } catch { /* best-effort */ }
}

// ─── Snapshot writers ──────────────────────────────────────────────────────
// Bot-owned markdown mirrors of in-process data. Operator reads these in
// Obsidian. Each function is fully independent and never throws.

function _ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

/** 20-Devs/_blacklist.md — mirror of getDevBlacklist() */
export async function writeDevBlacklistSnapshot() {
  try {
    const { getDevBlacklist } = await import("./dev-blacklist.js");
    const vaultDir = _getVaultWriterDir();
    const dir = path.join(vaultDir, "20-Devs");
    _ensureDir(dir);
    const bl = getDevBlacklist();
    const now = new Date().toISOString();
    const recent = (bl.entries || []).slice(0, 12);
    const tiers = { CRITICAL: [], HIGH: [], MEDIUM: [], LOW: [] };
    for (const e of recent) {
      const t = e.tier || "LOW";
      if (tiers[t]) tiers[t].push(e);
    }
    const tierLines = t => tiers[t].map(e => {
      const exp  = e.expires_at ? ` expires ${e.expires_at.slice(0, 10)}` : "";
      const rugs = e.rug_count > 1 ? ` (${e.rug_count}×)` : "";
      return `- \`${(e.creator || "?").slice(0, 12)}…\`${rugs} — ${(e.reason || "").slice(0, 50)}${exp}`;
    }).join("\n");

    const body =
      `---\ntype: bot-snapshot\nupdated: ${now}\ntotal: ${bl.total}\ncritical: ${bl.critical}\nhigh: ${bl.high}\nmedium: ${bl.medium}\nlow: ${bl.low}\n---\n\n` +
      `# Dev Blacklist — ${bl.total} active (${bl.critical} CRITICAL, ${bl.high} HIGH, ${bl.medium} MEDIUM, ${bl.low} LOW)\n\n` +
      `_Auto-generated. Edit \`dev-overrides.md\` to trust/distrust a dev._\n\n` +
      (tiers.CRITICAL.length ? `## CRITICAL (permanent)\n${tierLines("CRITICAL")}\n\n` : "") +
      (tiers.HIGH.length     ? `## HIGH (30d)\n${tierLines("HIGH")}\n\n`    : "") +
      (tiers.MEDIUM.length   ? `## MEDIUM (14d)\n${tierLines("MEDIUM")}\n\n` : "") +
      (tiers.LOW.length      ? `## LOW (7d)\n${tierLines("LOW")}\n\n`       : "") +
      (bl.total === 0 ? "_No entries yet._\n" : "");
    atomicWriteText(path.join(dir, "_blacklist.md"), body);
  } catch { /* best-effort */ }
}

/** 10-SmartMoney/_live.md — mirror of top discovered wallets */
export async function writeSmartMoneyLive() {
  try {
    const { listDiscoveredWallets } = await import("./wallet-discovery.js");
    const vaultDir = _getVaultWriterDir();
    const dir = path.join(vaultDir, "10-SmartMoney");
    _ensureDir(dir);
    const wallets = listDiscoveredWallets({ qualified_only: true, limit: 20 });
    const now     = new Date().toISOString();
    const count   = wallets.length;
    const avgWr   = count > 0
      ? wallets.reduce((s, w) => s + (w.stats?.win_rate || 0), 0) / count
      : 0;
    const topSyms = wallets
      .flatMap(w => (w.source_tokens || []).slice(0, 2))
      .filter((s, i, a) => s && a.indexOf(s) === i)
      .slice(0, 6)
      .join(", ");

    const rows = wallets.slice(0, 15).map(w => {
      const addr = (w.address || "?").slice(0, 8) + "…";
      const wr   = w.stats?.win_rate != null ? `${(w.stats.win_rate * 100).toFixed(0)}%` : "?";
      const pnl  = w.stats?.realized_pnl_sol != null ? `${w.stats.realized_pnl_sol.toFixed(2)}` : "?";
      const tr   = w.stats?.total_trades || 0;
      return `| ${addr} | ${wr} | ${pnl} | ${tr} |`;
    }).join("\n");

    const body =
      `---\ntype: bot-snapshot\nupdated: ${now}\nwallet_count: ${count}\navg_winrate: ${avgWr.toFixed(3)}\ntop_symbols: "${topSyms}"\n---\n\n` +
      `# Smart Money — Top Proven Wallets\n\n` +
      `_Auto-generated. Edit \`follow-overrides.md\` to boost/mute wallets._\n\n` +
      `${count} qualified wallets tracked${avgWr > 0 ? ` | avg win rate ${(avgWr * 100).toFixed(0)}%` : ""}\n\n` +
      (rows ? `| wallet | win rate | PnL (SOL) | trades |\n|--------|----------|-----------|--------|\n${rows}\n` : "_No qualified wallets yet._\n");
    atomicWriteText(path.join(dir, "_live.md"), body);
  } catch { /* best-effort */ }
}

/** 30-Narratives/_heat.md — mirror of getNarrativeHeat() */
export async function writeNarrativeHeat() {
  try {
    const { getNarrativeHeat } = await import("./narratives.js");
    const vaultDir = _getVaultWriterDir();
    const dir      = path.join(vaultDir, "30-Narratives");
    _ensureDir(dir);
    const heat = getNarrativeHeat({ min_trades: 2, include_emerging: true });
    const now  = new Date().toISOString();

    const mkRow = n => {
      const wr  = n.winrate != null ? `${(n.winrate * 100).toFixed(0)}%` : "?";
      const pnl = n.avg_pnl_pct != null ? `${n.avg_pnl_pct > 0 ? "+" : ""}${n.avg_pnl_pct.toFixed(0)}%` : "?";
      return `| ${n.narrative} | ${wr} | ${pnl} | ${n.trades || "?"} |`;
    };
    const tbl = arr => arr.length
      ? `| narrative | win rate | avg PnL | trades |\n|-----------|----------|---------|--------|\n${arr.map(mkRow).join("\n")}\n`
      : "_None yet._\n";

    const hotItems  = heat.hot_items      || heat.ranked?.filter(n => n.winrate >= 0.55) || [];
    const coldItems = heat.cold_items     || heat.ranked?.filter(n => n.winrate < 0.4)   || [];
    const emItems   = heat.emerging_items || heat.emerging_list?.map(name => ({ narrative: name, tier: "emerging" })) || [];

    const body =
      `---\ntype: bot-snapshot\nupdated: ${now}\n---\n\n` +
      `# Narrative Heat\n\n` +
      `_Auto-generated. Adjust \`focus_narrative\` / \`blacklist_narratives\` in \`operator-notes.md\` to override._\n\n` +
      `## 🔥 Hot (winning)\n${tbl(hotItems)}\n` +
      `## ❄️ Cold (losing)\n${tbl(coldItems)}\n` +
      `## 🌱 Emerging (watch)\n${tbl(emItems)}\n`;
    atomicWriteText(path.join(dir, "_heat.md"), body);
  } catch { /* best-effort */ }
}

/** 40-RugPatterns/_active.md — mirror of listPatterns(), with vault-approve side-effect */
export async function writeActiveRugPatterns() {
  try {
    const { listPatterns, approvePattern } = await import("./rug-patterns.js");
    const { getPatternOverrides } = await import("./vault-reader.js");
    const vaultDir = _getVaultWriterDir();
    const dir      = path.join(vaultDir, "40-RugPatterns");
    _ensureDir(dir);
    const pats      = listPatterns();
    const overrides = getPatternOverrides();
    const now       = new Date().toISOString();

    // Apply vault-approved patterns (idempotent)
    for (const id of overrides.approve) {
      try { approvePattern(id, { approvedBy: "vault-operator" }); } catch { /* skip */ }
    }
    const muted = new Set(overrides.mute);

    const seedRows = (pats.seed_patterns || []).slice(0, 10).map(p =>
      `- \`${p.id || p.name}\` (w${p.weight || "?"}) — ${(p.description || p.reason || "").slice(0, 60)}`
    ).join("\n") || "_None._";

    const learnedRows = (pats.learned_patterns || []).slice(0, 15).map(p => {
      const mutedTag  = muted.has(p.id) ? " 🔇 MUTED" : "";
      const statusTag = p.review_status === "approved" ? " ✅" : " ⏳ PENDING REVIEW";
      const conf      = p.confidence != null ? ` conf ${p.confidence.toFixed(2)}` : "";
      const occ       = p.occurrences != null ? ` ${p.occurrences}×` : "";
      return `- \`${p.id}\` (w${p.weight || "?"}${conf}${occ})${statusTag}${mutedTag} — ${(p.description || "").slice(0, 50)}`;
    }).join("\n") || "_None learned yet._";

    const body =
      `---\ntype: bot-snapshot\nupdated: ${now}\nseed_count: ${pats.seed}\nlearned_count: ${pats.learned}\npending_review: ${pats.pending_learned}\n---\n\n` +
      `# Rug Patterns — ${pats.seed} seed, ${pats.learned} learned (${pats.pending_learned} pending review)\n\n` +
      `_Auto-generated. Add IDs to \`pattern-overrides.md\` (\`approve_patterns\` / \`mute_patterns\`) to act._\n\n` +
      `## Seed (hard rules)\n${seedRows}\n\n` +
      `## Learned (auto)\n${learnedRows}\n`;
    atomicWriteText(path.join(dir, "_active.md"), body);
  } catch { /* best-effort */ }
}

/** 50-Chains/_status.md — per-chain condition, wallet, strategy, execution flag */
export async function writeChainStatus() {
  try {
    const { getAllChainIntelligence } = await import("../market-chain-intel.js");
    const { getActiveStrategyId, getActiveStrategyIds } = await import("../strategies.js");
    const { config } = await import("../config.js");

    const vaultDir = _getVaultWriterDir();
    const dir = path.join(vaultDir, "50-Chains");
    _ensureDir(dir);

    const intel      = getAllChainIntelligence(); // { chain: { chain, score, condition, metrics, ts } }
    const activeCfg  = Array.isArray(config.gmgn?.chains) && config.gmgn.chains.length
      ? config.gmgn.chains : ["sol"];
    const execEnabled = !!config.gmgn?.execEnabled;
    const evmWallets  = (config.gmgn?.wallets && typeof config.gmgn.wallets === "object")
      ? config.gmgn.wallets : {};
    const solWallet   = config.wallet?.address || "";
    const stratIds    = getActiveStrategyIds();
    const primaryStrat = getActiveStrategyId() || "scalping";
    const now = new Date().toISOString();

    // Build frontmatter: one key per chain for easy parsing
    const fmLines = ["type: bot-snapshot", `updated: ${now}`, `primary_strategy: ${primaryStrat}`];
    const KNOWN = ["sol", "base", "bsc", "eth"];

    const statusRows = [];
    const fmChains = {};

    for (const chain of KNOWN) {
      const snap    = intel[chain] || {};
      const inCfg   = activeCfg.includes(chain);
      const cond    = snap.condition || (inCfg ? "UNKNOWN" : "OFF");
      const score   = snap.score != null ? snap.score : "—";
      const wallet  = chain === "sol"
        ? (solWallet ? solWallet.slice(0, 8) + "…" : "—")
        : (evmWallets[chain] ? evmWallets[chain].slice(0, 10) + "…" : "—");
      const exec    = chain === "sol" ? "Jupiter" : (execEnabled && evmWallets[chain] ? "GMGN" : "OFF");
      const discovery = inCfg ? "ON" : "OFF";
      // Store compact chain state in frontmatter for vault-reader
      fmChains[chain] = `${cond}|${score}|${discovery}|${exec}`;

      const condIcon = { HOT: "🔥", EXTREME: "🚀", NORMAL: "⚪", COLD: "❄️", DEAD: "💀", UNKNOWN: "❓", OFF: "⬛" }[cond] ?? "❓";
      statusRows.push(
        `| ${condIcon} ${chain.padEnd(4)} | ${String(cond).padEnd(7)} | ${String(score).padStart(3)} | ${wallet.padEnd(12)} | ${primaryStrat.padEnd(10)} | ${discovery.padEnd(9)} | ${exec} |`
      );
    }

    for (const [chain, val] of Object.entries(fmChains)) {
      fmLines.push(`chain_${chain}: "${val}"`);
    }

    const body =
      `---\n${fmLines.join("\n")}\n---\n\n` +
      `# Chain Status\n\n` +
      `_Auto-generated. Edit \`chain-overrides.md\` to set preferred_strategy or disable_chains._\n\n` +
      `Active strategies: ${stratIds.join(", ") || primaryStrat}\n\n` +
      `| chain | condition | score | wallet | strategy | discovery | execution |\n` +
      `|-------|-----------|-------|--------|----------|-----------|-----------|\n` +
      `${statusRows.join("\n")}\n`;

    atomicWriteText(path.join(dir, "_status.md"), body);
  } catch { /* best-effort */ }
}

/**
 * 01-Context/strategy-performance.md — bot-written analysis of what's working.
 * Reads from lessons.js trade history + narrative heat. LLM uses this to pick
 * strategies and market conditions to prioritise.
 */
export async function writeStrategyInsights() {
  try {
    const { getPerformanceSummary, getPerformanceHistory } = await import("../lessons.js");
    const { getNarrativeHeat, getNarrativeHeatPrompt } = await import("./narratives.js");

    const vaultDir = _getVaultWriterDir();
    const dir = path.join(vaultDir, "01-Context");
    _ensureDir(dir);

    const perfSummary = getPerformanceSummary();
    const trades = getPerformanceHistory({ limit: 50 });
    const now = new Date().toISOString();

    // Aggregate per-strategy
    const stratStats = {};
    const condStats = {};
    const narrativeStats = {};
    for (const t of trades) {
      const s  = t.strategy_used || "scalping";
      const c  = t.market_condition || "UNKNOWN";
      const ns = Array.isArray(t.narrative_tags) ? (t.narrative_tags[0] || "other") : "other";
      for (const [key, map] of [[s, stratStats], [c, condStats], [ns, narrativeStats]]) {
        if (!map[key]) map[key] = { wins: 0, total: 0, pnl: 0 };
        map[key].total++;
        if (t.win) map[key].wins++;
        map[key].pnl += (t.pnl_pct || 0);
      }
    }

    const mkTable = (map, label, minTrades = 2) => {
      const rows = Object.entries(map)
        .filter(([, s]) => s.total >= minTrades)
        .sort((a, b) => (b[1].wins / b[1].total) - (a[1].wins / a[1].total))
        .map(([id, s]) => {
          const wr = s.total > 0 ? ((s.wins / s.total) * 100).toFixed(0) : "?";
          const avg = (s.pnl / Math.max(1, s.total)).toFixed(1);
          const icon = s.total > 0 && s.wins / s.total >= 0.55 ? "✅" : "⚠️";
          return `${icon} ${id}: ${wr}% wr | ${avg}% avg | ${s.total} trades`;
        });
      return rows.length > 0 ? `${label}\n${rows.join("\n")}` : "";
    };

    const stratTable  = mkTable(stratStats,  "## Strategy (win rate)", 1);
    const condTable   = mkTable(condStats,   "## Market Condition",    1);
    const narrTable   = mkTable(narrativeStats, "## Narrative",        2);
    const heatPrompt  = getNarrativeHeatPrompt();

    // Recommendation: best strategy + market condition
    const bestStrat = Object.entries(stratStats)
      .filter(([, s]) => s.total >= 3)
      .sort((a, b) => b[1].wins / b[1].total - a[1].wins / a[1].total)[0];
    const bestCond  = Object.entries(condStats)
      .filter(([, s]) => s.total >= 3)
      .sort((a, b) => b[1].wins / b[1].total - a[1].wins / a[1].total)[0];
    const worstCond = Object.entries(condStats)
      .filter(([, s]) => s.total >= 3)
      .sort((a, b) => a[1].wins / a[1].total - b[1].wins / b[1].total)[0];

    const recLines = [];
    if (bestStrat)  recLines.push(`Best strategy:   ${bestStrat[0]} (${(bestStrat[1].wins/bestStrat[1].total*100).toFixed(0)}% wr, ${bestStrat[1].total} trades)`);
    if (bestCond)   recLines.push(`Best condition:  ${bestCond[0]} (${(bestCond[1].wins/bestCond[1].total*100).toFixed(0)}% wr)`);
    if (worstCond)  recLines.push(`Avoid condition: ${worstCond[0]} (${(worstCond[1].wins/worstCond[1].total*100).toFixed(0)}% wr — reduce size or skip)`);

    const body =
      `---\ntype: bot-snapshot\nupdated: ${now}\ntrade_count: ${trades.length}\n---\n\n` +
      `# Strategy Performance (last ${trades.length} trades)\n\n` +
      `_Auto-generated every 5 min. LLM reads this before each screening decision._\n\n` +
      `**Summary:** ${typeof perfSummary === "string" ? perfSummary : JSON.stringify(perfSummary)}\n\n` +
      (recLines.length > 0 ? `## Recommendations\n${recLines.join("\n")}\n\n` : "") +
      (stratTable  ? `${stratTable}\n\n`  : "") +
      (condTable   ? `${condTable}\n\n`   : "") +
      (narrTable   ? `${narrTable}\n\n`   : "") +
      (heatPrompt  ? `## Narrative Heat\n${heatPrompt}\n`  : "");

    atomicWriteText(path.join(dir, "strategy-performance.md"), body);
  } catch { /* best-effort */ }
}

/** 60-Learning/_darwin.md — what the darwin loop has learned: signal fitness + shadow outcomes */
export async function writeDarwinLearning() {
  try {
    const { getDarwinAnalytics } = await import("../lessons.js");
    const { getShadowStats } = await import("./shadow-watchlist.js");

    const vaultDir = _getVaultWriterDir();
    const dir = path.join(vaultDir, "60-Learning");
    _ensureDir(dir);

    const analytics = getDarwinAnalytics(); // sorted by weight desc
    const shadow    = getShadowStats();
    const now       = new Date().toISOString();

    // Compact frontmatter encodings (name:weight|wr%|uses) for the reader.
    const enc = s => `${s.signal}:${s.weight.toFixed(2)}|${(s.win_rate * 100).toFixed(0)}|${s.total_uses}`;
    const proven = analytics.filter(s => s.total_uses >= 3 && s.weight >= 1.1).slice(0, 4);
    const weak   = analytics.filter(s => s.total_uses >= 3 && s.weight <= 0.9).slice(-4);

    const rows = analytics.map(s => {
      const trend = s.weight >= 1.1 ? "📈" : s.weight <= 0.9 ? "📉" : "➖";
      return `| ${trend} ${s.signal} | ${s.weight.toFixed(2)} | ${(s.win_rate * 100).toFixed(0)}% | ${s.total_uses} |`;
    }).join("\n");

    const srcRows = Object.entries(shadow.by_source || {})
      .sort((a, b) => (b[1].rugged + (b[1].mooned || 0)) - (a[1].rugged + (a[1].mooned || 0)))
      .slice(0, 8)
      .map(([src, s]) => `| ${src} | ${s.total ?? "?"} | ${s.rugged ?? 0} | ${s.mooned ?? 0} |`)
      .join("\n");

    const body =
      `---\ntype: bot-snapshot\nupdated: ${now}\nsignals_tracked: ${analytics.length}\n` +
      `proven_signals: "${proven.map(enc).join(", ")}"\nweak_signals: "${weak.map(enc).join(", ")}"\n` +
      `shadow_watching: ${shadow.watching || 0}\nshadow_rugged: ${shadow.rugged || 0}\n` +
      `shadow_mooned: ${shadow.mooned || 0}\nshadow_survived: ${shadow.survived || 0}\n---\n\n` +
      `# Darwin Learning — Signal Fitness\n\n` +
      `_Auto-generated. Weights learned from trade closes + shadow outcomes (rugs avoided / winners missed)._\n` +
      `_Weight > 1 = component proved itself; < 1 = component votes for losers. Applied to aggregateSignal each screening._\n\n` +
      (rows
        ? `| signal | weight | win rate | samples |\n|--------|--------|----------|---------|\n${rows}\n\n`
        : "_No learned signals yet — weights accumulate from trade closes and shadow outcomes._\n\n") +
      `## Shadow Watchlist (learning without buying)\n\n` +
      `Watching ${shadow.watching || 0} | rugs avoided ${shadow.rugged || 0} | winners missed ${shadow.mooned || 0} | survived ${shadow.survived || 0}\n\n` +
      (srcRows ? `| source | watched | rugged | mooned |\n|--------|---------|--------|--------|\n${srcRows}\n` : "");

    atomicWriteText(path.join(dir, "_darwin.md"), body);
  } catch { /* best-effort */ }
}

/**
 * Create template operator files on first vault intelligence activation.
 * Called once; templates guide the operator on how to write lessons.
 */
export async function ensureIntelligenceTemplates() {
  try {
    const vaultDir = _getVaultWriterDir();

    // operator-lessons.md
    const lessonsFile = path.join(vaultDir, "operator-lessons.md");
    if (!fs.existsSync(lessonsFile)) {
      atomicWriteText(lessonsFile,
        `# Operator Lessons\n\n` +
        `_Tulis wisdom trading kamu di sini. Bot membaca ini sebelum setiap keputusan screening._\n` +
        `_Format bebas — tulis seperti instruksi untuk trading assistant._\n\n` +
        `## Kapan Entry\n` +
        `- Market HOT + narrative AI/agent = prioritas entry, ukuran penuh\n` +
        `- Market COLD = hanya entry jika conviction > 70 + smart money confirmed\n` +
        `- Jam 08-16 UTC = prime window memecoin\n\n` +
        `## Kapan Skip\n` +
        `- Chain base atau bsc dalam kondisi DEAD atau COLD = skip\n` +
        `- Token dengan rug_score > 45 = skip meski conviction tinggi\n` +
        `- Narrative casino/gambling = selalu skip\n` +
        `- Token baru < 30 menit listing = too early, skip\n\n` +
        `## Strategi per Kondisi\n` +
        `- HOT: scalping agresif, entry cepat\n` +
        `- NORMAL: momentum strategy, tunggu konfirmasi\n` +
        `- COLD: dip_buy only, ukuran sangat kecil\n` +
        `- DEAD: no entry\n\n` +
        `## Taktik Khusus\n` +
        `- (tambah pelajaran kamu dari trading nyata di sini)\n` +
        `- Contoh: "dev wallet X selalu dump dalam 30 menit — hindari"\n`
      );
    }

    // 08-MoneyManagement/sizing-guidance.md
    const mmDir = path.join(vaultDir, "08-MoneyManagement");
    if (!fs.existsSync(mmDir)) fs.mkdirSync(mmDir, { recursive: true });
    const mmFile = path.join(mmDir, "sizing-guidance.md");
    if (!fs.existsSync(mmFile)) {
      atomicWriteText(mmFile,
        `# Money Management Rules\n\n` +
        `_Rules untuk position sizing dan risk management. Bot membaca ini sebelum menentukan ukuran entry._\n\n` +
        `## Position Sizing\n` +
        `- Market HOT: maksimal 40% bankroll per posisi\n` +
        `- Market NORMAL: maksimal 25% bankroll per posisi\n` +
        `- Market COLD: maksimal 15% bankroll per posisi\n` +
        `- Conviction < 40: pakai 75% dari ukuran normal\n` +
        `- Conviction > 75: boleh ukuran penuh\n\n` +
        `## Risk Limits\n` +
        `- Stop loss maksimal: -20% per posisi\n` +
        `- Daily loss limit: -10% dari total bankroll → berhenti trading hari itu\n` +
        `- Maksimal 3 posisi terbuka bersamaan\n` +
        `- Jangan hold lebih dari 2 posisi di narrative yang sama\n\n` +
        `## Exit Rules\n` +
        `- Trailing stop aktif setelah +5% gain\n` +
        `- Ambil profit sebagian (50%) saat +20% untuk kurangi risiko\n` +
        `- Jika rug signal naik saat posisi open: tutup di -15% atau lebih awal\n\n` +
        `## Capital Preservation\n` +
        `- Setelah 3 loss berturut-turut: pause 1 jam\n` +
        `- Jangan revenge trade setelah rug\n`
      );
    }
  } catch { /* best-effort */ }
}

/**
 * Refresh all vault snapshots. Called on the 5-min cron.
 * Each snapshot runs independently — one failure never blocks the others.
 */
/**
 * 00-Overview/_engine-reality.md — the LIVE deterministic engine parameters
 * (task #21). The vault's prose rules guide the LLM; THIS file states what
 * the machine actually enforces, so the two can never silently diverge (the
 * operator-notes said "rug > 45 skip" while the real gate was 35 for days).
 */
export async function writeEngineReality() {
  try {
    const { config } = await import("../config.js");
    const { getActiveStrategyIds, getStrategy } = await import("../strategies.js");
    const { getVaultOverrides } = await import("./vault-reader.js");

    const vaultDir = _getVaultWriterDir();
    const dir = path.join(vaultDir, "00-Overview");
    _ensureDir(dir);

    const ov = getVaultOverrides();
    const cfgGate = config.screening?.maxEntryRugScore ?? 60;
    const gateLine = ov.max_entry_rug_score != null
      ? `**${ov.max_entry_rug_score}** (OVERRIDE operator-notes frontmatter; config=${cfgGate})`
      : `**${cfgGate}** (config)`;

    const stratIds = (() => { try { return getActiveStrategyIds() || []; } catch { return []; } })();
    const stratRows = stratIds.map((id) => {
      try {
        const s = getStrategy(id) || {};
        const sl = Number.isFinite(s.stoploss) ? `${(s.stoploss * 100).toFixed(0)}%` : "—";
        const trail = s.trailing_stop?.positive_offset != null
          ? `aktif +${(s.trailing_stop.positive_offset * 100).toFixed(0)}%, drop ${((s.trailing_stop.positive_distance ?? 0) * 100).toFixed(0)}%` : "—";
        const lim = config.positionLimits?.perStrategy?.[id]?.maxPositions ?? "—";
        return `| ${id} | ${sl} | ${trail} | ${lim} |`;
      } catch { return `| ${id} | ? | ? | ? |`; }
    }).join("\n");

    const onOff = (v) => (v ? "ON" : "off");
    const body = `---
tags: [engine, auto-generated]
updated: ${new Date().toISOString()}
type: engine-reality
---

# ⚙️ Engine Reality — Parameter Mesin LIVE

> [!warning] AUTO-GENERATED — jangan diedit
> File ini adalah sumber kebenaran tentang apa yang MESIN benar-benar lakukan.
> Aturan prosa di operator-notes/money-management membimbing LLM; file ini
> menyatakan gate deterministiknya. Untuk menyetir mesin dari Obsidian, pakai
> frontmatter operator-notes.md (mis. \`max_entry_rug_score: 45\`, clamp 10-60).

## Entry
- Rug gate (hard-block): ${gateLine}
- Pause trading: ${ov.pause_trading ? "⛔ YA (operator)" : "tidak"}
- Mcap cap operator: ${ov.skip_mcap_above != null ? `$${ov.skip_mcap_above}` : "—"}

## Exit & Posisi (per strategi aktif)
| Strategi | Stop Loss | Trailing (aktif/drop) | Max Posisi |
| -------- | --------- | --------------------- | ---------- |
${stratRows || "| (tidak ada strategi aktif) | | | |"}

- Partial take-profit: belum dijalankan mesin (sedang diuji cf-exit:ptp-50-25)
- Fast-exit sentinel: ${onOff(config.fastExit?.enabled)}${config.fastExit?.enabled ? ` (${config.fastExit.intervalSec ?? 20}s, hard-drop ${config.fastExit.hardDropPct ?? -35}%)` : ""}

## Guards
- Capital guard: ${onOff(config.capitalGuard?.enabled)} | Streak sizer: ${onOff(config.streakSizer?.enabled)} | R:R guard: ${onOff(config.rrGuard?.enabled)}
- Learning-mode pause per loss: ${config.pilot?.learningModeDurationMin ?? "?"} menit
`;
    atomicWriteText(path.join(dir, "_engine-reality.md"), body);
  } catch { /* best-effort, never throws */ }
}

export async function refreshVaultSnapshots() {
  await Promise.allSettled([
    writeDevBlacklistSnapshot(),
    writeSmartMoneyLive(),
    writeNarrativeHeat(),
    writeActiveRugPatterns(),
    writeChainStatus(),
    writeStrategyInsights(),
    writeDarwinLearning(),
    writeEngineReality(),
  ]);
}
